[workspace]
resolver = "3"
members = [
  "./problems/median-of-sorted-arrays/",
  "./problems/palindromic-substring",
  "./problems/regular-expression-matching",
]

[profile.release]
debug = true

[alias]
flamegraph = "!cargo-flamegraph"
